SectionVerb {
	EnableSequence [
		cset "name='Headphone Switch' off"
		cset "name='Speaker Switch' on"
		cset "name='Speaker Playback Volume' 85%"
		cset "name='Internal Mic Switch' on"
		cset "name='Capture Volume' 80%"
	]
	DisableSequence [
		cset "name='Speaker Switch' off"
		cset "name='Headphone Switch' off"
	]
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Internal Stereo Speakers"

	EnableSequence [
		cset "name='Headphone Switch' off"
		cset "name='Speaker Switch' on"
	]

	DisableSequence [
		cset "name='Speaker Switch' off"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixerElem "Speaker"
		PlaybackVolume "Speaker Playback Volume"
		PlaybackSwitch "Speaker Switch"
	}
}

SectionDevice."Headphones" {
	Comment "Headphone Jack"

	EnableSequence [
		cset "name='Speaker Switch' off"
		cset "name='Headphone Switch' on"
	]

	DisableSequence [
		cset "name='Headphone Switch' off"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixerElem "Headphone"
		PlaybackVolume "Headphone Playback Volume"
		PlaybackSwitch "Headphone Switch"
		JackControl "Headphone Jack"
		JackHWMute "Speaker"
	}
}

SectionDevice."Mic" {
	Comment "Internal Digital Microphone"

	EnableSequence [
		cset "name='Headset Mic Switch' off"
		cset "name='Internal Mic Switch' on"
	]

	DisableSequence [
		cset "name='Internal Mic Switch' off"
	]

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},1"
		CaptureMixerElem "Internal Mic"
		CaptureVolume "Internal Mic Playback Volume"
		CaptureSwitch "Internal Mic Switch"
	}
}

SectionDevice."Headset" {
	Comment "Headset Combo Microphone"

	EnableSequence [
		cset "name='Internal Mic Switch' off"
		cset "name='Headset Mic Switch' on"
	]

	DisableSequence [
		cset "name='Headset Mic Switch' off"
	]

	Value {
		CapturePriority 200
		CapturePCM "hw:${CardId},1"
		CaptureMixerElem "Headset Mic"
		CaptureVolume "Headset Mic Playback Volume"
		CaptureSwitch "Headset Mic Switch"
		JackControl "Headset Mic Jack"
	}
}
